import { PrismaClient, Services } from '@prisma/client';
const prisma = new PrismaClient();

const SERVICES = [
  { name: '3D Rendering' },
  { name: 'Air Conditioning Installation' },
  { name: 'Aluminum Fence Repair' },
  { name: 'Antique Furniture Sales' },
  { name: 'Appliance Removal' },
  { name: 'Architectural Design' },
  { name: 'Art Selection' },
  { name: 'Asphalt Paving' },
  { name: 'Attic Restoration' },
  { name: 'Aboveground Pool Liner Replacement' },
  { name: 'Air Conditioning Repair' },
  { name: 'Aluminum Siding' },
  { name: 'Antique Restoration' },
  { name: 'Appliance Repair' },
  { name: 'Architectural Drawings' },
  { name: 'Artificial Grass Installation' },
  { name: 'Asphalt Shingle Roofing' },
  { name: 'Automatic Gate Installation' },
  { name: 'Aboveground Pools' },
  { name: 'Air Duct Cleaning' },
  { name: 'Ant Control' },
  { name: 'Appliance Installation' },
  { name: 'Appliance Sales' },
  { name: 'Architectural Photography' },
  { name: 'Artificial Living Walls' },
  { name: 'Attic Conversion' },
  { name: 'Awning Installation' },
  { name: 'Aerial Photography' },
  { name: 'Aluminum Fence Installation' },
  { name: 'Antenna Installation' },
  { name: 'Appliance Refinishing' },
  { name: 'Arbor Design and Construction' },
  { name: 'Art Installation' },
  { name: 'Asbestos Removal' },
  { name: 'Attic Insulation' },
  { name: 'Awning Repair' },
  { name: 'Backsplash Installation' },
  { name: 'Baseboard Installation' },
  { name: 'Bathroom Plumbing' },
  { name: 'Bathtub Repair' },
  { name: 'Bee Removal' },
  { name: 'Biohazard Cleanup' },
  { name: 'Blind Installation' },
  { name: 'Brick Masonry' },
  { name: 'Brush Clearing' },
  { name: 'Balcony Design & Construction' },
  { name: 'Basement Design' },
  { name: 'Bathroom Remodeling' },
  { name: 'Bathtub Sales' },
  { name: 'Bicycle Storage' },
  { name: 'Bird Removal' },
  { name: 'Blinds & Shades Sales' },
  { name: 'Brick Repair' },
  { name: 'Building Design' },
  { name: 'Baluster Installation' },
  { name: 'Basement Waterproofing' },
  { name: 'Bathtub Installation' },
  { name: 'Bed Bug Removal' },
  { name: 'Bifold Doors' },
  { name: 'Blacksmith' },
  { name: 'Boiler Installation' },
  { name: 'Brick Sales' },
  { name: 'Barn Design & Construction' },
  { name: 'Bathroom Design' },
  { name: 'Bathtub Refinishing' },
  { name: 'Bedroom Design' },
  { name: 'Bifold Windows' },
  { name: 'Blind Cleaning' },
  { name: 'Boiler Repair' },
  { name: 'Brick Siding' },
  { name: 'Cabinet Installation' },
  { name: 'Cabinet Repair' },
  { name: 'Carpet Cleaning' },
  { name: 'Carpet Stretching' },
  { name: 'Ceiling Fan Repair' },
  { name: 'Chimney Cleaning' },
  { name: 'Circuit Breaker Installation & Repair' },
  { name: 'Color Consulting' },
  { name: 'Concrete Countertops' },
  { name: 'Concrete Sales' },
  { name: 'Cooktop, Range & Stove Repair' },
  { name: 'Countertop Sales' },
  { name: 'Custom Basketball Courts' },
  { name: 'Custom Blinds & Shades' },
  { name: 'Custom Cabinet Doors' },
  { name: 'Custom Drapery' },
  { name: 'Custom Fire Pits' },
  { name: 'Custom Folding Doors' },
  { name: 'Custom Home Bars' },
  { name: 'Custom Kitchen Cabinets' },
  { name: 'Custom Pantries' },
  { name: 'Custom Putting Greens' },
  { name: 'Custom Shelving' },
  { name: 'Custom Tennis Courts' },
  { name: 'Custom Walk-in Closets' },
  { name: 'Cabinet Painting' },
  { name: 'Cabinet Sales' },
  { name: 'Carpet Installation' },
  { name: 'Carport Installation' },
  { name: 'Ceiling Painting' },
  { name: 'Chimney Construction' },
  { name: 'Closet Design' },
  { name: 'Composition Roofing' },
  { name: 'Concrete Driveway Installation' },
  { name: 'Concrete Sealing' },
  { name: 'Countertop Installation' },
  { name: 'Countertop and Tile Sealing' },
  { name: 'Custom Bathroom Vanities' },
  { name: 'Custom Bocce Ball Courts' },
  { name: 'Custom Cabinets' },
  { name: 'Custom Embroidery' },
  { name: 'Custom Fireplace Mantels' },
  { name: 'Custom Framing' },
  { name: 'Custom Homes' },
  { name: 'Custom Millwork' },
  { name: 'Custom Playhouses' },
  { name: 'Custom Retractable Screens' },
  { name: 'Custom Storage' },
  { name: 'Custom Treehouses' },
  { name: 'Custom Water Features' },
  { name: 'Cabinet Refacing' },
  { name: 'Cable Installation' },
  { name: 'Carpet Repair' },
  { name: 'Cedar Siding' },
  { name: 'Chain Link Fence Installation' },
  { name: 'Chimney Inspection' },
  { name: 'Closet Organization' },
  { name: 'Concrete Cleaning' },
  { name: 'Concrete Flooring' },
  { name: 'Concrete Staining' },
  { name: 'Countertop Refinishing' },
  { name: 'Crown Molding Installation' },
  { name: 'Custom Batting Cages' },
  { name: 'Custom Bookcases' },
  { name: 'Custom Closet Doors' },
  { name: 'Custom Entertainment Centers' },
  { name: 'Custom Fireplaces' },
  { name: 'Custom Furniture' },
  { name: 'Custom Hot Tubs' },
  { name: 'Custom Molding' },
  { name: 'Custom Playsets' },
  { name: 'Custom Rugs' },
  { name: 'Custom Swing Sets' },
  { name: 'Custom Upholstery' },
  { name: 'Custom Windows' },
  { name: 'Cabinet Refinishing' },
  { name: 'Carpentry' },
  { name: 'Carpet Sales' },
  { name: 'Ceiling Fan Installation' },
  { name: 'Childproofing' },
  { name: 'Chimney Repair' },
  { name: 'Cockroach Control' },
  { name: 'Concrete Construction' },
  { name: 'Concrete Repair' },
  { name: 'Cooktop, Range & Stove Installation' },
  { name: 'Countertop Repair' },
  { name: 'Custom Artwork' },
  { name: 'Custom Beds' },
  { name: 'Custom Built-ins' },
  { name: 'Custom Countertops' },
  { name: 'Custom Exterior Doors' },
  { name: 'Custom Flooring' },
  { name: 'Custom Garage Doors' },
  { name: 'Custom Interior Doors' },
  { name: 'Custom Murphy Beds' },
  { name: 'Custom Pool Tables' },
  { name: 'Custom Sculptures' },
  { name: 'Custom Table' },
  { name: 'Custom Volleyball Courts' },
  { name: 'Deck Building' },
  { name: 'Deck Refinishing' },
  { name: 'Decluttering' },
  { name: 'Demolition' },
  { name: 'Dishwasher Repair' },
  { name: 'Door Repair' },
  { name: 'Drafting' },
  { name: 'Drip Irrigation Installation' },
  { name: 'Driveway Sealing' },
  { name: 'Dryer Repair' },
  { name: 'Drywall Repair' },
  { name: 'Deck Cleaning' },
  { name: 'Deck Repair' },
  { name: 'Decorative Concrete' },
  { name: 'Design Consultation' },
  { name: 'Dock Design & Construction' },
  { name: 'Door Sales' },
  { name: 'Drain Cleaning' },
  { name: 'Driveway Gate Installation' },
  { name: 'Drought Tolerant Landscaping' },
  { name: 'Dryer Vent Cleaning' },
  { name: 'Drywall Texturing' },
  { name: 'Deck Design' },
  { name: 'Deck Staining' },
  { name: 'Decorative Painting' },
  { name: 'Dining Room Design' },
  { name: 'Dog Run Construction' },
  { name: 'Double Glazing' },
  { name: 'Drain Services' },
  { name: 'Driveway Repair' },
  { name: 'Dry Wells' },
  { name: 'Dryer Vent Installation' },
  { name: 'Dumpster Rental' },
  { name: 'Deck Lighting Installation' },
  { name: 'Deck Waterproofing' },
  { name: 'Dehumidification' },
  { name: 'Dishwasher Installation' },
  { name: 'Door Painting' },
  { name: 'Downsizing' },
  { name: 'Drapery Cleaning' },
  { name: 'Driveway Resurfacing' },
  { name: 'Dryer Installation' },
  { name: 'Drywall Installation' },
  { name: 'Earthen Flooring' },
  { name: 'Electric Fireplace Installation' },
  { name: 'Electrical Outlet & Light Switch Installation' },
  { name: 'Emergency Plumbing' },
  { name: 'Excavating' },
  { name: 'Exterior Painting' },
  { name: 'Earthquake Retrofitting' },
  { name: 'Electric Fireplace Repair' },
  { name: 'Electrical Repair' },
  { name: 'Energy-Efficient Homes' },
  { name: 'Exhaust Fan Installation' },
  { name: 'Exterior Shades' },
  { name: 'Edible Gardens' },
  { name: 'Electrical Inspection' },
  { name: 'Elevator Installation' },
  { name: 'Entry Design' },
  { name: 'Exterior Door Installation' },
  { name: 'Exterior Shutters' },
  { name: 'Egress Windows' },
  { name: 'Electrical Installation' },
  { name: 'Elevator Repair' },
  { name: 'Epoxy Flooring' },
  { name: 'Exterior House Cleaning' },
  { name: 'Faucet Installation' },
  { name: 'Fence Installation' },
  { name: 'Fiber Cement Siding' },
  { name: 'Fireplace Repair' },
  { name: 'Floor Leveling' },
  { name: 'Floor Sanding' },
  { name: 'Foundation Construction' },
  { name: 'Freezer Repair' },
  { name: 'Furnace Repair' },
  { name: 'Furniture Removal' },
  { name: 'Furniture Selection' },
  { name: 'Faucet Repair' },
  { name: 'Fence Repair' },
  { name: 'Finish Carpentry' },
  { name: 'Fireplace Sales' },
  { name: 'Floor Plans' },
  { name: 'Flooring Installation' },
  { name: 'Foundation Monitoring' },
  { name: 'Frozen Pipe Repair' },
  { name: 'Furniture Assembly' },
  { name: 'Furniture Rental' },
  { name: 'Faucet Sales' },
  { name: 'Fence Sales' },
  { name: 'Fire Damage Restoration' },
  { name: 'Fireproofing' },
  { name: 'Floor Polishing' },
  { name: 'Flooring Sales' },
  { name: 'Foundation Repair' },
  { name: 'Furnace Cleaning' },
  { name: 'Furniture Delivery' },
  { name: 'Furniture Repair' },
  { name: 'Faux Painting' },
  { name: 'Feng Shui Design' },
  { name: 'Fireplace Installation' },
  { name: 'Floor Cleaning' },
  { name: 'Floor Refinishing' },
  { name: 'Folding Patio Doors' },
  { name: 'Freezer Installation' },
  { name: 'Furnace Installation' },
  { name: 'Furniture Refinishing' },
  { name: 'Furniture Sales' },
  { name: 'GFCI Outlet Installation' },
  { name: 'Garage Door Sales' },
  { name: 'Garbage Disposal Installation' },
  { name: 'Gas Fireplace Repair' },
  { name: 'Gas to Electric Conversion' },
  { name: 'Gazebo Design & Construction' },
  { name: 'Geothermal Heat Pump' },
  { name: 'Glass Railings' },
  { name: 'Green Building' },
  { name: 'Grout Cleaning and Sealing' },
  { name: 'Gutter Covers' },
  { name: 'Garage Building' },
  { name: 'Garage Floor Coating' },
  { name: 'Garbage Disposal Repair' },
  { name: 'Gas Leak Detection' },
  { name: 'Gate Installation' },
  { name: 'General Contracting' },
  { name: 'Glass Block Installation' },
  { name: 'Glass Repair' },
  { name: 'Green Cleaning' },
  { name: 'Grout Repair' },
  { name: 'Gutter Installation' },
  { name: 'Garage Design' },
  { name: 'Garage Floor Refinishing' },
  { name: 'Garden Design' },
  { name: 'Gas Leak Repair' },
  { name: 'Gate Repair' },
  { name: 'Generator Installation' },
  { name: 'Glass Cutting' },
  { name: 'Graffiti Removal' },
  { name: 'Green Roofing' },
  { name: 'Guesthouse Design & Construction' },
  { name: 'Gutter Repair' },
  { name: 'Garage Door Installation' },
  { name: 'Garage Storage' },
  { name: 'Gas Fireplace Installation' },
  { name: 'Gas Pipe Installation' },
  { name: 'Gate Sales' },
  { name: 'Generator Repair' },
  { name: 'Glass Installation' },
  { name: 'Granite Countertops' },
  { name: 'Greenhouse Design & Construction' },
  { name: 'Gutter Cleaning' },
  { name: 'HVAC Inspection' },
  { name: 'Hardscaping' },
  { name: 'Heating Sales' },
  { name: 'Holiday Decorating' },
  { name: 'Home Energy Audit' },
  { name: 'Home Restoration' },
  { name: 'Home Theater Design' },
  { name: 'House Cleaning' },
  { name: 'Humidifier Installation' },
  { name: 'HVAC Installation' },
  { name: 'Heat Pump Installation' },
  { name: 'Heating System Installation' },
  { name: 'Holiday Lighting' },
  { name: 'Home Gym Design & Construction' },
  { name: 'Home Security Companies & Installation' },
  { name: 'Home Theater Installation' },
  { name: 'House Framing' },
  { name: 'Hurricane Shutter Installation' },
  { name: 'HVAC Repair' },
  { name: 'Heat Pump Repair' },
  { name: 'Hedge Trimming' },
  { name: 'Home Audio System' },
  { name: 'Home Inspection' },
  { name: 'Home Security System Repair' },
  { name: 'Hot Tub Installation' },
  { name: 'House Plans' },
  { name: 'Hurricane Shutter Repair' },
  { name: 'Handicap-Accessible Design' },
  { name: 'Heating Repair' },
  { name: 'Historic Building Conservation' },
  { name: 'Home Automation' },
  { name: 'Home Office Design & Construction' },
  { name: 'Home Staging' },
  { name: 'Hot Tub Sales' },
  { name: 'House Wiring' },
  { name: 'Hydro Jetting' },
  { name: 'Ice Machine Repair' },
  { name: 'Insulation Installation' },
  { name: 'Interior Painting' },
  { name: 'Ice Removal' },
  { name: 'Interior Design' },
  { name: 'Interior Shutters' },
  { name: 'In-Ground Trampolines' },
  { name: 'Interior Design Photography' },
  { name: 'Irrigation Repair' },
  { name: 'Indoor Air Quality Testing' },
  { name: 'Interior Door Installation' },
  { name: 'Irrigation System Installation' },
  { name: 'Junk Removal' },
  { name: 'Kids Bedroom Design' },
  { name: 'Kitchen Design' },
  { name: 'Kitchen Plumbing' },
  { name: 'Kitchen Remodeling' },
  { name: 'Laminate Countertops' },
  { name: 'Lamp Repair' },
  { name: 'Landscape Construction' },
  { name: 'Landscape Maintenance' },
  { name: 'Lawn Aeration' },
  { name: 'Lawn Treatment & Fertilization' },
  { name: 'Leather Repair' },
  { name: 'Linoleum Flooring Installation' },
  { name: 'Living Walls' },
  { name: 'Long Distance Moving' },
  { name: 'Laminate Flooring Installation' },
  { name: 'Land Clearing' },
  { name: 'Landscape Design' },
  { name: 'Landscape Plans' },
  { name: 'Lawn Care' },
  { name: 'Lead Paint Inspection' },
  { name: 'Lighting Design' },
  { name: 'Linoleum Flooring Repair' },
  { name: 'Local Moving' },
  { name: 'Lumber Sales' },
  { name: 'Laminate Flooring Repair' },
  { name: 'Land Leveling & Grading' },
  { name: 'Landscape Drainage System Installation' },
  { name: 'Landscape Supplies' },
  { name: 'Lawn Mowing' },
  { name: 'Lead Paint Removal' },
  { name: 'Lighting Installation' },
  { name: 'Linoleum Flooring Sales' },
  { name: 'Locksmith' },
  { name: 'Luxury Vinyl Tile Sales' },
  { name: 'Laminate Flooring Sales' },
  { name: 'Land Surveying' },
  { name: 'Landscape Lighting Installation' },
  { name: 'Laundry Room Design' },
  { name: 'Lawn Seeding' },
  { name: 'Leaf Removal' },
  { name: 'Lighting Sales' },
  { name: 'Living Room Design' },
  { name: 'Log Home Construction' },
  { name: 'Marble Countertops' },
  { name: 'Metal Roofing' },
  { name: 'Mirror Repair' },
  { name: 'Mold Removal & Remediation' },
  { name: 'Mudroom Design' },
  { name: 'Masonry' },
  { name: 'Microwave Installation' },
  { name: 'Modular Home Additions' },
  { name: 'Mosquito Control' },
  { name: 'Mulching' },
  { name: 'Metal Countertops' },
  { name: 'Microwave Repair' },
  { name: 'Modular Home Construction' },
  { name: 'Motorized Blinds' },
  { name: 'Multigenerational Homes' },
  { name: 'Metal Fabrication' },
  { name: 'Mirror Installation' },
  { name: 'Mold Inspection' },
  { name: 'Mudjacking' },
  { name: 'Mural Painting' },
  { name: 'Natural Stone Countertops' },
  { name: 'Natural Swimming Pools' },
  { name: 'New Home Construction' },
  { name: 'Nursery Design' },
  { name: 'Oil to Gas Conversion' },
  { name: 'Outdoor Fireplace Construction' },
  { name: 'Outdoor Lighting Design' },
  { name: 'Organic Gardens' },
  { name: 'Outdoor Furniture Sales' },
  { name: 'Outdoor Lighting Installation' },
  { name: 'Oriental Rug Cleaning' },
  { name: 'Outdoor Kitchen Construction' },
  { name: 'Oven Installation' },
  { name: 'Outdoor Audio Installation' },
  { name: 'Outdoor Kitchen Design' },
  { name: 'Oven Repair' },
  { name: 'PAT Testing' },
  { name: 'Passive Solar Heating & Cooling' },
  { name: 'Pellet Stove Installation' },
  { name: 'Pet Door Installation' },
  { name: 'Plaster Repair' },
  { name: 'Plumbing Repair' },
  { name: 'Pool Cleaning & Maintenance' },
  { name: 'Pool Filter Cleaning' },
  { name: 'Pool Liner Replacement' },
  { name: 'Pool Tiling' },
  { name: 'Potted Plants' },
  { name: 'Project Management' },
  { name: 'Paint Removal' },
  { name: 'Patio Construction' },
  { name: 'Pellet Stove Repair' },
  { name: 'Piano Moving' },
  { name: 'Plastering' },
  { name: 'Polished Concrete' },
  { name: 'Pool Covers' },
  { name: 'Pool House Design & Construction' },
  { name: 'Pool Plastering' },
  { name: 'Pool and Spa Repair' },
  { name: 'Prefab Houses' },
  { name: 'Propane Sales and Refills' },
  { name: 'Paint Sales' },
  { name: 'Patio Design' },
  { name: 'Pergola Construction' },
  { name: 'Plantation Shutters' },
  { name: 'Playroom Design' },
  { name: 'Pond Construction' },
  { name: 'Pool Deck Design & Construction' },
  { name: 'Pool Landscaping' },
  { name: 'Pool Remodeling' },
  { name: 'Popcorn Ceiling Removal' },
  { name: 'Pressure Washing' },
  { name: 'Propane Tank Installation' },
  { name: 'Pantry Design' },
  { name: 'Paver Installation' },
  { name: 'Pest Control' },
  { name: 'Planting' },
  { name: 'Plumbing Inspection' },
  { name: 'Pool & Spa Equipment Sales' },
  { name: 'Pool Fencing' },
  { name: 'Pool Lighting Installation' },
  { name: 'Pool Table Repair' },
  { name: 'Porch Design & Construction' },
  { name: 'Professional Organizing' },
  { name: 'Quartz Countertops' },
  { name: 'Quartzite Countertops' },
  { name: 'Radiant Floor Heating' },
  { name: 'Range Hood Installation' },
  { name: 'Refrigerator Installation' },
  { name: 'Retaining Wall Construction' },
  { name: 'Roof Flashing Repair' },
  { name: 'Roof Installation' },
  { name: 'Rooftop Deck Installation' },
  { name: 'Radon Mitigation' },
  { name: 'Range Hood Sales' },
  { name: 'Refrigerator Repair' },
  { name: 'Rodent Control' },
  { name: 'Roof Heating' },
  { name: 'Roof Repair' },
  { name: 'Rototilling' },
  { name: 'Railing Installation' },
  { name: 'Real Estate Photography' },
  { name: 'Residential Window Film' },
  { name: 'Roof Cleaning' },
  { name: 'Roof Ice Melt Systems' },
  { name: 'Roof Replacement' },
  { name: 'Rubber Roofing' },
  { name: 'Railing Repair' },
  { name: 'Recessed Lighting Installation' },
  { name: 'Residential Window Tinting' },
  { name: 'Roof Flashing Installation' },
  { name: 'Roof Inspection' },
  { name: 'Roof Waterproofing' },
  { name: 'Rug Cleaning' },
  { name: 'Sandblasting' },
  { name: 'Security Camera Installation' },
  { name: 'Septic Tank Repair' },
  { name: 'Shelving Installation' },
  { name: 'Shower Installation' },
  { name: 'Siding Sales' },
  { name: 'Skylight Installation' },
  { name: 'Sliding Door Repair' },
  { name: 'Smoke Detector Installation' },
  { name: 'Soffit Repair' },
  { name: 'Solar Pool Heating' },
  { name: 'Soundproofing' },
  { name: 'Spray Foam Insulation' },
  { name: 'Stained Glass Repair & Design' },
  { name: 'Stamped Concrete' },
  { name: 'Stone Masonry' },
  { name: 'Stretch Ceilings' },
  { name: 'Stump Grinding' },
  { name: 'Sump Pump Repair' },
  { name: 'Swamp Cooler Installation' },
  { name: 'Sauna Installation' },
  { name: 'Septic Tank Cleaning' },
  { name: 'Sewer Cleaning' },
  { name: 'Shower Door Installation' },
  { name: 'Shower Sales' },
  { name: 'Sink Sales' },
  { name: 'Skylight Repair' },
  { name: 'Small Appliance Repair' },
  { name: 'Snow Removal' },
  { name: 'Solar Panel Cleaning' },
  { name: 'Solar Tube Installation' },
  { name: 'Space Planning' },
  { name: 'Sprinkler Repair' },
  { name: 'Stair Installation' },
  { name: 'Steel Fabrication' },
  { name: 'Stone Sales' },
  { name: 'Structural Engineering' },
  { name: 'Stump Removal' },
  { name: 'Sunroom Design & Construction' },
  { name: 'Swamp Cooler Repair' },
  { name: 'Sauna Repair' },
  { name: 'Septic Tank Installation' },
  { name: 'Sewer Line Repair' },
  { name: 'Shower Door Repair' },
  { name: 'Siding Installation' },
  { name: 'Site Planning' },
  { name: 'Slate Roofing' },
  { name: 'Smart Homes' },
  { name: 'Sod Installation' },
  { name: 'Solar Panel Installation' },
  { name: 'Solar Water Heating' },
  { name: 'Spider Control' },
  { name: 'Sprinkler System Installation' },
  { name: 'Stair Repair' },
  { name: 'Stone Cleaning' },
  { name: 'Stone Siding' },
  { name: 'Stucco Installation' },
  { name: 'Subfloor Installation' },
  { name: 'Surround Sound Installation' },
  { name: 'Swimming Pool Construction' },
  { name: 'Sauna Sales' },
  { name: 'Septic Tank Pumping' },
  { name: 'Shed Design & Construction' },
  { name: 'Shower Door Sales' },
  { name: 'Siding Repair' },
  { name: 'Site Preparation' },
  { name: 'Sliding Door Installation' },
  { name: 'Smart Lighting' },
  { name: 'Soffit Installation' },
  { name: 'Solar Panel Repair' },
  { name: 'Solid Surface Countertops' },
  { name: 'Sports Equipment Storage' },
  { name: 'Sprinkler Winterization' },
  { name: 'Staircase Design' },
  { name: 'Stone Installation' },
  { name: 'Storm Shelter Construction' },
  { name: 'Stucco Repair' },
  { name: 'Sump Pump Installation' },
  { name: 'Sustainable Design' },
  { name: 'Swimming Pool Design' },
  { name: 'TV Installation' },
  { name: 'Termite Control' },
  { name: 'Thermostat Installation' },
  { name: 'Tile Installation' },
  { name: 'Tiny House Construction' },
  { name: 'Torch Down Roofing' },
  { name: 'Trellis Construction' },
  { name: 'Tankless Water Heater Installation' },
  { name: 'Texture Painting' },
  { name: 'Thermostat Repair' },
  { name: 'Tile Repair' },
  { name: 'Toilet Installation' },
  { name: 'Tree Planting' },
  { name: 'Trenchless Sewer Repair' },
  { name: 'Tankless Water Heater Repair' },
  { name: 'Thatched Roofing' },
  { name: 'Tile Countertops' },
  { name: 'Tile Roofing' },
  { name: 'Toilet Repair' },
  { name: 'Tree Pruning' },
  { name: 'Trim Work' },
  { name: 'Tar and Gravel Roofing' },
  { name: 'Thatched Roofing Repair' },
  { name: 'Tile Cutting' },
  { name: 'Tile Sales' },
  { name: 'Toilet Sales' },
  { name: 'Tree Removal' },
  { name: 'Under Deck Ceiling Installation' },
  { name: 'Upholstery Cleaning' },
  { name: 'Upholstery Repair' },
  { name: 'Vanity Installation' },
  { name: 'Vinyl Floor Repair' },
  { name: 'Ventilation Installation & Repair' },
  { name: 'Vinyl Flooring Installation' },
  { name: 'Videography' },
  { name: 'Vinyl Flooring Sales' },
  { name: 'Vinyl Fence Installation' },
  { name: 'Vinyl Siding' },
  { name: 'Wainscoting' },
  { name: 'Wallcovering Sales' },
  { name: 'Washing Machine Repair' },
  { name: 'Water Heater Repair' },
  { name: 'Water Main Repair' },
  { name: 'Water Testing' },
  { name: 'Weather Stripping' },
  { name: 'Well Pump Installation' },
  { name: 'Window Installation' },
  { name: 'Window Screen Installation' },
  { name: 'Wine Cellar Installation' },
  { name: 'Wood Fence Repair' },
  { name: 'Wood Floor Refinishing' },
  { name: 'Wood Siding' },
  { name: 'Wrought Iron Fence Installation' },
  { name: 'Wall Stenciling' },
  { name: 'Wallpaper Installation' },
  { name: 'Wasp Control' },
  { name: 'Water Leak Detection' },
  { name: 'Water Removal' },
  { name: 'Water Treatment System Installation' },
  { name: 'Weed Control' },
  { name: 'Wheelchair Ramp Installation' },
  { name: 'Window Repair' },
  { name: 'Window Screen Repair' },
  { name: 'Wood Chipping' },
  { name: 'Wood Finishing' },
  { name: 'Wood Floor Repair' },
  { name: 'Wood Stove Installation' },
  { name: 'Wrought Iron Fence Repair' },
  { name: 'Wall Texture Removal' },
  { name: 'Wallpaper Removal' },
  { name: 'Water Damage Restoration' },
  { name: 'Water Line Installation' },
  { name: 'Water Softener Installation' },
  { name: 'Water Well Repair' },
  { name: 'Welding' },
  { name: 'Wildlife & Animal Removal' },
  { name: 'Window Replacement' },
  { name: 'Window Washing' },
  { name: 'Wood Countertops' },
  { name: 'Wood Floor Installation' },
  { name: 'Wood Floor Staining' },
  { name: 'Wood Stove Repair' },
  { name: 'Wall Upholstery' },
  { name: 'Washing Machine Installation' },
  { name: 'Water Heater Installation' },
  { name: 'Water Main Installation' },
  { name: 'Water Softener Repair' },
  { name: 'Waterproofing' },
  { name: 'Well Drilling' },
  { name: 'Window Caulking' },
  { name: 'Window Sales' },
  { name: 'Wine Cellar Design' },
  { name: 'Wood Fence Installation' },
  { name: 'Wood Floor Polishing' },
  { name: 'Wood Flooring Sales' },
  { name: 'Workshop Design & Construction' },
  { name: 'Yard Waste Removal' },
];

const CATEGORIES = [
  { name: 'Building Design' },
  { name: 'Custom Homes' },
  { name: 'Drafting' },
  { name: 'Energy-Efficient Homes' },
  { name: 'Floor Plans' },
  { name: 'Green Building' },
  { name: 'Historic Building Conservation' },
  { name: 'Garage Building' },
  { name: 'Bathroom Remodeling' },
  { name: 'Carport Installation' },
  { name: 'Crown Molding Installation' },
  { name: 'Custom Home Bars' },
  { name: 'Demolition' },
  { name: 'Drywall Installation' },
  { name: 'Drywall Repair' },
  { name: 'House Framing' },
  { name: 'House Plans' },
  { name: 'Land Surveying' },
  { name: 'New Home Construction' },
  { name: 'Site Planning' },
  { name: 'Interior design' },
  { name: 'Color Consulting' },
  { name: 'Downsizing' },
  { name: 'Holiday Decorating' },
  { name: 'Kids Bedroom Design' },
  { name: 'Bathroom Design' },
  { name: 'Kitchen Design' },
  { name: 'Pantry Design' },
  { name: 'Handicap-Accessible Design' },
  { name: 'Outdoor Kitchen Design' },
  { name: 'Design Consultation' },
  { name: 'Bathtub Refinishing' },
  { name: 'Glass Block Installation' },
  { name: 'Kitchen Remodeling' },
  { name: 'Outdoor Kitchen Construction' },
  { name: 'Sauna Installation' },
  { name: 'Shower Installation' },
  { name: 'Garden Design' },
  { name: 'Hardscaping' },
  { name: 'Landscape Design' },
  { name: 'Landscape Plans' },
  { name: 'Patio Design' },
  { name: 'Pool Landscaping' },
  { name: 'Edible Gardens' },
  { name: 'Artificial Grass Installation' },
  { name: 'Brush Clearing' },
  { name: 'Custom Fire Pits' },
  { name: 'Custom Water Features' },
  { name: 'Drought Tolerant Landscaping' },
  { name: 'Dry Wells' },
  { name: 'Excavating' },
  { name: 'Complete Home Remodeling' },
  { name: 'Bathroom Renovation' },
  { name: 'Basement Remodeling' },
  { name: 'Apartment Remodeling' },
  { name: 'Room Addition Construction' },
  { name: 'Second-Story Addition' },
  { name: 'Garage Conversion' },
  { name: 'Sunroom Installation' },
  { name: 'In-law Suite Construction' },
  { name: 'Bump-Out Addition' },
  { name: 'Porch or Deck Addition' },
  { name: 'Aluminum Siding' },
  { name: 'Brick Siding' },
  { name: 'Cedar Siding' },
  { name: 'Plaster Repair' },
  { name: 'Plastering' },
  { name: 'Siding Installation' },
  { name: 'Siding Repair' },
  { name: 'Electric Fireplace Installation' },
  { name: 'Electric Fireplace Repair' },
  { name: 'Fireplace Installation' },
  { name: 'Fireplace Repair' },
  { name: 'Gas Fireplace Installation' },
  { name: 'Gas Fireplace Repair' },
  { name: 'Outdoor Fireplace Construction' },
  { name: 'Garage Door Sales & Repair' },
  { name: 'Building Supplies' },
  { name: 'Brick Masonry' },
  { name: 'Brick Repair' },
  { name: 'Concrete Cleaning' },
  { name: 'Concrete Construction' },
  { name: 'Concrete Repair' },
  { name: 'Foundation Construction' },
  { name: 'Masonry' },
  { name: 'Mudjacking' },
  { name: 'Specialty Contractors' },
  { name: 'Baluster Installation' },
  { name: 'Railing Installation' },
  { name: 'Railing Repair' },
  { name: 'Stair Installation' },
  { name: 'Stair Repair' },
  { name: 'Staircase Design' },
  { name: 'Glass Railings' },
  { name: 'Wine Cellars' },
  { name: 'Countertop Installation' },
  { name: 'Countertop Repair' },
  { name: 'Custom Countertops' },
  { name: 'Countertop Sales' },
  { name: 'Concrete Countertops' },
  { name: 'Marble Countertops' },
  { name: 'Granite Countertops' },
  { name: 'Quartz Countertops' },
  { name: 'Backsplash Installation' },
  { name: 'Tile Installation' },
  { name: 'Tile Repair' },
  { name: 'Tile Sales' },
  { name: 'Tile Countertops' },
  { name: 'Stone Installation' },
  { name: 'Complete Basement Remodeling' },
  { name: 'Basement Waterproofing' },
  { name: 'Basement Finishing' },
  { name: 'Basement Flooring Installation' },
  { name: 'Basement Egress Window Installation' },
  { name: 'Bedding & Bath' },
  { name: 'Cabinet Installation' },
  { name: 'Cabinet Refacing' },
  { name: 'Cabinet Repair' },
  { name: 'Custom Bathroom Vanities' },
  { name: 'Custom Bookcases' },
  { name: 'Custom Built-ins' },
  { name: 'Custom Cabinet Doors' },
  { name: 'Custom Cabinets' },
  { name: 'Cabinet Refinishing' },
  { name: 'Finish Carpentry' },
  { name: 'Custom Windows' },
  { name: 'Window Treatment Services' },
  { name: 'Window Repair' },
  { name: 'Carpet Dealers' },
  { name: 'Door Dealers' },
  { name: 'Environmental Services & Restoration' },
  { name: 'Flooring Installation' },
  { name: 'Laminate Flooring Installation' },
  { name: 'Laminate Flooring Repair' },
  { name: 'Linoleum Flooring Installation' },
  { name: 'Linoleum Flooring Repair' },
  { name: 'Vinyl Floor Repair' },
  { name: 'Vinyl Flooring Installation' },
  { name: 'Furniture & Accessories' },
  { name: 'Furniture Repair & Upholstery' },
  { name: 'Glass Installation' },
  { name: 'Glass Repair' },
  { name: 'Shower Door Installation' },
  { name: 'Shower Door Repair' },
  { name: 'Shower Door Sales' },
  { name: 'Stained Glass Repair & Design' },
  { name: 'Double Glazing' },
  { name: 'Mirror Repair' },
  { name: 'Ironwork' },
  { name: 'Kitchen & Bath Fixtures' },
  { name: 'Lighting Design' },
  { name: 'Lighting Sales' },
  { name: 'Window Contractors' },
  { name: 'Accessible Bathroom Design' },
  { name: 'Wheelchair Ramp Installation' },
  { name: 'Grab Bar Installation' },
  { name: 'Door Widening' },
  { name: 'Accessible Kitchen Design' },
  { name: 'Barrier-Free Home Modifications' },
  { name: 'Universal Design Consultation' },
  { name: 'Backyard Courts' },
  { name: 'Deck Building' },
  { name: 'Deck Lighting Installation' },
  { name: 'Deck Refinishing' },
  { name: 'Deck Repair' },
  { name: 'Deck Staining' },
  { name: 'Deck Waterproofing' },
  { name: 'Gazebo Design & Construction' },
  { name: 'Asphalt Paving' },
  { name: 'Concrete Driveway Installation' },
  { name: 'Driveway Repair' },
  { name: 'Driveway Resurfacing' },
  { name: 'Driveway Sealing' },
  { name: 'Land Leveling & Grading' },
  { name: 'Sandblasting' },
  { name: 'Fence Installation' },
  { name: 'Fence Repair' },
  { name: 'Gate Installation' },
  { name: 'Gate Repair' },
  { name: 'Vinyl Fence Installation' },
  { name: 'Garden & Landscape Supplies' },
  { name: 'Gardeners & Lawn Care' },
  { name: 'Hot Tub & Spa Dealers' },
  { name: 'Outdoor Lighting & Audio Visual Systems' },
  { name: 'Outdoor Play Systems' },
  { name: 'Spa & Pool Maintenance' },
  { name: 'Swimming Pool Design' },
  { name: 'Swimming Pool Construction' },
  { name: 'Aboveground Pools' },
  { name: 'Pool Remodeling' },
  { name: 'Natural Swimming Pools' },
  { name: 'Pool Plastering' },
  { name: 'Pool Tiling' },
  { name: 'Tree Services' },
  { name: 'Closet Design' },
  { name: 'Custom Walk-in Closets' },
  { name: 'Closet Organization' },
  { name: 'Bicycle Storage' },
  { name: 'Custom Storage' },
  { name: 'Garage Storage' },
  { name: 'Decluttering' },
  { name: 'Professional Organizing' },
  { name: 'Sports Equipment Storage' },
  { name: 'Custom Artists' },
  { name: 'Handyman' },
  { name: 'Home Staging' },
  { name: 'Furniture Selection' },
  { name: 'Space Planning' },
  { name: 'Art Selection' },
  { name: 'Accessory Selection' },
  { name: 'Movers' },
  { name: 'Paint & Wall Coverings' },
  { name: 'Ceiling Painting' },
  { name: 'Door Painting' },
  { name: 'Exterior Painting' },
  { name: 'Faux Painting' },
  { name: 'Interior Painting' },
  { name: 'Lead Paint Inspection' },
  { name: 'Lead Paint Removal' },
  { name: 'Photographers' },
  { name: 'Real Estate Agents' },
  { name: 'Roofing & Gutters' },
  { name: 'Window Treatments' },
  { name: 'Appliances' },
  { name: 'Electricians' },
  { name: 'Home Automation' },
  { name: 'Home Security Companies & Installation' },
  { name: 'Home Theater Installation' },
  { name: 'Security Camera Installation' },
  { name: 'Surround Sound Installation' },
  { name: 'TV Installation' },
  { name: 'Home Theater Design' },
  { name: 'Air Conditioning & Heating' },
  { name: 'Plumbers' },
  { name: 'Septic Tank Systems' },
  { name: 'Home Energy Audit' },
  { name: 'Solar Panel Installation' },
  { name: 'Solar Pool Heating' },
  { name: 'Solar Water Heating' },
  { name: 'Solar Panel Cleaning' },
  { name: 'Solar Panel Repair' },
  { name: 'Carpet & Upholstery Cleaners' },
  { name: 'Chimney Cleaners' },
  { name: 'Exterior Cleaners' },
  { name: 'House Cleaners' },
  { name: 'Junk Removal' },
  { name: 'Pest Control' },
  { name: 'Window Cleaners' },
];

const SKILLS = [
  { name: 'Plumbing' },
  { name: 'Drywall Repair' },
  { name: 'Sheetrock' },
  { name: 'Door Installation' },
  { name: 'Caulking' },
  { name: 'Demo' },
  { name: 'Window Installation' },
  { name: 'Hardwood Floors' },
  { name: 'HVAC' },
  { name: 'Sub Contractors' },
  { name: 'Light Fixtures' },
  { name: 'Kitchen Cabinets' },
  { name: 'Exterior Painting' },
  { name: 'Tiling' },
  { name: 'RAN' },
  { name: 'Rental Properties' },
  { name: 'Construction Projects' },
  { name: 'Residential Homes' },
  { name: 'Room Additions' },
  { name: 'Commercial Buildings' },
  { name: 'Drywall Installation' },
  { name: 'General Construction' },
  { name: 'Plastering' },
  { name: 'Tile Installation' },
  { name: 'Residential Construction' },
  { name: 'Home Maintenance' },
  { name: 'Shingles' },
  { name: 'Residential Properties' },
  { name: 'Cabinet Installation' },
  { name: 'Counter Tops' },
  { name: 'Window Replacement' },
];

async function main() {
  const skill = await prisma.skill.findFirst({
    where: {
      name: {
        equals: 'Plumbing',
      },
    },
  });

  if (!skill) {
    await prisma.projectOnSkills.deleteMany({});
    await prisma.skill.deleteMany({});
    await prisma.skill.createMany({
      data: SKILLS,
    });
  }

  const category = await prisma.category.findFirst({
    where: {
      name: {
        equals: 'Room Addition Construction',
      },
    },
  });

  if (!category) {
    await prisma.categoriesOnProjects.deleteMany({});
    await prisma.categoriesOnBusinesses.deleteMany({});
    await prisma.categoryOnBusinessProject.deleteMany({});
    await prisma.category.deleteMany({});
    await prisma.category.createMany({
      data: CATEGORIES,
    });
  }

  const service = await prisma.services.findFirst({
    where: {
      name: {
        equals: '3D Rendering',
      },
    },
  });

  if (!service) {
    await prisma.servicesOnBusinesses.deleteMany({});
    await prisma.services.deleteMany({});
    await prisma.services.createMany({
      data: SERVICES,
    });
  }

  const resService = await prisma.services.findMany({
    where: {
      OR: [
        {
          name: {
            equals: 'Architectural Design',
          },
        },
        {
          name: {
            equals: 'Arbor Design and Construction',
          },
        },
        {
          name: {
            equals: 'Basement Design',
          },
        },
      ],
    },
  });

  const resServiceIds = resService.map((rs) => rs.id);

  await prisma.services.updateMany({
    where: {
      id: {
        in: resServiceIds,
      },
    },
    data: {
      isDesigner: true,
    },
  });

  // Designers Part
  /* const existInviteData = await prisma.projectInvitation.findMany();

  if (existInviteData && existInviteData.length !== 0) {
    await prisma.projectInvitation.deleteMany();
  } */

  // Contract part
  /* const existContract = await prisma.contracts.findMany();

  if (existContract && existContract.length !== 0) {
    await prisma.milestonesOnContracts.deleteMany();
    await prisma.contractsFile.deleteMany();
    await prisma.contracts.deleteMany();
  } */
}

main();
