import React from 'react';
import Script from 'next/script';
import './globals.css';

const G_TAG = 'G-JGWMTJVLFF';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script
          type="text/javascript"
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_API_KEY}&libraries=places,drawing&callback=`}
          async
          defer
        ></Script>
      </head>
      <Script async src={`https://www.googletagmanager.com/gtag/js?id=${G_TAG}`}></Script>
      <Script id="google-tag-manager" strategy="afterInteractive">
        {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', '${G_TAG}');`}
      </Script>
      <body className="font-karla min-h-[100%] text-content-primary">{children}</body>
    </html>
  );
}
